### ISSUE TITLE
Global optional arguments

### ISSUE THREAD

**Issue by dorneanu** [datafolklabs/cement#293]
Hi again,

I have 2 controller: Base and Parser. In Base I have:

```python
class BaseController(controller.CementBaseController):

    class Meta:
        label = 'base'
        description = "application"
        config_defaults = dict(
            debug = False,
            foo='bar', some_other_option='my default value',
        )

        arguments = [
            (['-f', '--foo'], dict(action='store')),
            (['--log-level'],
                dict(action='store', dest='level',
                    choices=('debug', 'info', 'warn', 'error', 'critical'),
                    help='Change logging level')),

        ]

    @controller.expose(hide=True, aliases=['run'])
    def default(self):
        logger.error("Test error")
        logger.info("Test info")

```

Thosre are the allowed arguments:

```shell
python application.py --help                                                                                                                                                          1 ↵
usage: application.py (sub-commands ...) [options ...] {arguments ...}

application

commands:

  parser
    Parser controller

optional arguments:
  -h, --help            show this help message and exit
  --debug               toggle debug output
  --quiet               suppress all output
  -f FOO, --foo FOO
  --log-level {debug,info,warn,error,critical}
                        Change logging level

```

Especially the `log-level` argument should be passed "globally" to all other controller. However when I try to do that, I get:

```shell
$ python application.py parser.py --log-level info
usage: application.py (sub-commands ...) [options ...] {arguments ...}
application.py: error: unrecognized arguments: parser.py
```

The other way around doesn't work as well:

```shell
python application.py --log-level info parser       
usage: application.py (sub-commands ...) [options ...] {arguments ...}
application.py: error: unrecognized arguments: parser
```

Am I missing sth? Thx in advance.

**Comment by derks** [comment]
This is a limitation of the current CementBaseController, and how it formulates command line arguments and nested/embedded controllers, etc.  

At present, there is no easy way to inherit only specific arguments from a parent controller.  It is also not possible to process arguments on multiple controllers simultaneously. I thought that I already had an issue open for this, but I can't find it.

Essentially, the plan is to rework CementBaseController so that arguments are processed at every level, therefore the following would work:

```
$ myapp --log-file /path/to/myapp.log second-nested-controller --foo=bar
```


That is different then having a `global` argument... the following would not work:

```
$ myapp second-nested-controller --log-file /path/to/myapp.log
```


Because the `log-file` option doesn't exist under the nested controller.  What I've suggested before is that one might maintain a `COMMON_ARGS` constant, the all controllers start with.  For example:

```python
COMMON_ARGS = [
    ( ['--log-level'],
      dict(action='store', dest='level',
             choices=('debug', 'info', 'warn', 'error', 'critical'),
             help='Change logging level') ),
    ]

class MyController(CementBaseController):
    class Meta:
        arguments = COMMON_ARGS + [
            ( ['-f', '--foo'], dict(help="notorious foo option") ),
            ]
```

Essentially, every controller would have the `COMMON_ARGS`.  You could then maybe have like, a `post_argument_parsing` hook to handle `--log-level`:

```python
from cement.core import hook

def set_log_level(app):
    if app.pargs.level is not None:
        app.log.set_level(app.pargs.level)

hook.register('post_argument_parsing', set_log_level)
```

Untested... but that is where I would start.

**Comment by dorneanu** [comment]
Hmmm.. OK. I think I'm not the only one looking for one solution. But the one you've suggested looks promising. I'll let you know if that works for me. But nevertheless: Thanks for your effort and a great CLI framework! :)

**Comment by derks** [comment]
Thanks.  I hope to improve these areas in the next release.  I plan on picking up development on 2.6.x  hear pretty soon now that 2.4.x has been out and no issues for several months.

**Comment by dorneanu** [comment]
Your solution worked like a charm! :)

**Comment by derks** [comment]
This has now been refactored into the new `ArgparseController` that will eventually replace `CementBaseController`.

See: http://cement.readthedocs.org/en/latest/api/ext/ext_argparse/


Essentially, rather than having to duplicate the same option onto every controller... such as 'log-level', the controller now honors options throughout the entire change.  Meaning, a `global` option of `--log-level` belongs on the `base` controller, and would be passed as:

```
$ myapp --log-level ERROR [some-controller] --some-other-option {some-command}
```

The `ArgparseController` provides the ability for all controllers to handle their arguments (or other arguments) regardless of which controller/function is actually being dispatched.

Example:

```
class Base(ArgparseController):
    class Meta:
        label = 'base'

    def _post_argument_parsing(self):
        # this gets called in every controller after argument parsing, before command execution
        if self.app.pargs.log_level:
            self.app.log.set_level(self.app.pargs.log_level)
```


The above is just an example, it's untested... but provided to simply follow up with this discussion.  Please see the doc on the new capabilities of `cement.ext.ext_argparse.ArgparseController`.
