### ISSUE TITLE
What is the best way to change default logging format?

### ISSUE THREAD

**Issue by fxstein** [datafolklabs/cement#335]
I need to change the output format for all logging levels to the same format as used by debug. That is to start with date/timestamp and then the output. Would like to set this at the app class level for all my commands, plus add startup logging for various settings and versions.

Could not find an example for that.

Thanks!

**Comment by derks** [comment]
You simply need to override the meta options on `LoggingLogHandler` (the default log handler) or whatever you're using (I prefer `ColorLogHandler` but it requires external deps):

**myapp.py**

```python
from cement.core.foundation import CementApp
from cement.ext.ext_logging import LoggingLogHandler

LOG_FORMAT = '%(asctime)s (%(levelname)s) %(namespace)s : %(message)s'

class MyLogHandler(LoggingLogHandler):
    class Meta:
        file_format = LOG_FORMAT
        console_format = LOG_FORMAT
        debug_format = LOG_FORMAT

class MyApp(CementApp):
    class Meta:
        label = 'myapp'
        log_handler = MyLogHandler

with MyApp() as app:
    app.run()
    app.log.info('This is an info message')
```

**Comment by derks** [comment]
Also, all meta options are (or should be) documented throughout the API documentation:

 * http://cement.readthedocs.org/en/latest/api/ext/ext_logging/#cement-ext-ext-logging

**Comment by fxstein** [comment]
Thanks for the fast answer! Exactly what I needed.

Preferring the ColorLogHandler myself. Works great in e.g. Atom when running scripts from within the IDE. Have not found a way to keep the color logging in the output of supervisor via its web interface - but thats a different problem.

**Comment by derks** [comment]
I'd imagine that you're not getting color in the output of supervisor because you're not attached to a tty:

 * https://github.com/datafolklabs/cement/blob/master/cement/ext/ext_colorlog.py#L179


That bit is hard-coded and not configurable currently... but if you're not on a tty then `ColorLogHandler` falls back on whatever is configured as `ColorLogHandler.Meta.formatter_class_without_color`.  You could try sub-classing and overriding `ColorLogHandler._get_console_formatter` (not recommended but atleast to test and see if that would solve the problem).  You could also inject `CEMENT_TEST` into the environment variables which should trigger it to still use the color formatter class.

If either of those things work for you we could look at patching those bits to make it more configurable (a la meta or configuration options).

**Comment by derks** [comment]
@fxstein any word on this? Was curious about my last comment if the issue was because you were not running as a TTY (which disables color logging by default).  If it's off your radar, we can close it out... just curious.  Thanks.

**Comment by fxstein** [comment]
You are correct. Yes we can close this out. Thanks!
