### ISSUE TITLE
log_validator checks if warn method is available

### ISSUE THREAD

**Issue by barta0** [datafolklabs/cement#397]
The `log_validator` checks if warn method is available, but `ILog` interface has no method with this name, that should be implemented.

**Comment by derks** [comment]
@barta0 thanks for that.. this is due to a recent change in 2.10.  Previously the interface defined that a handler implement `warn()`... it is now, `warning()`, but I forgot to remove that from the validator.  For the interrim you can just make `warn()` call `self.warning()` until next release when this is fixed.
