### ISSUE TITLE
Unandled exception if ArgparseController is missing default function

### ISSUE THREAD

**Issue by jtpereyda** [datafolklabs/cement#426]
Using `ArgparseController` without a `default` command results in an unhandled exception.

Code:
```python
from cement.core.foundation import CementApp
from cement.ext.ext_argparse import ArgparseController, expose


class MyBaseController(ArgparseController):
    @expose(help='<Subcommand description>')
    def subcommand(self):
        self.app.log.info("subcommand successful")


class MyApp(CementApp):
    class Meta:
        label = 'demo'
        handlers = [MyBaseController]


with MyApp() as app:
    app.run()
```

The help output looks as expected:
```
> python3 demo4.py --help
usage: demo [-h] [--debug] [--quiet] {subcommand} ...

optional arguments:
  -h, --help    show this help message and exit
  --debug       toggle debug output
  --quiet       suppress all output

sub-commands:
  {subcommand}
    subcommand  <Subcommand description>
```

But running with no command raises an exception:
```
> python3 demo4.py
Traceback (most recent call last):
  File "demo4.py", line 18, in <module>
    app.run()
  File "C:\Python34\lib\site-packages\cement\core\foundation.py", line 882, in run
    return_val = self.controller._dispatch()
  File "C:\Python34\lib\site-packages\cement\ext\ext_argparse.py", line 927, in _dispatch
    (contr.__class__.__name__, func_name))      # pragma: nocover
cement.core.exc.FrameworkError: Controller function does not exist MyBaseController.default()
```

It seems that, if there is no default function, the best thing would be to output a parse error, as if the user had typed in an invalid function.

Otherwise, I take it that the default function is required by cement, in which case a doc update might be appropriate: http://builtoncement.com/2.10/api/ext/ext_argparse.html#cement-ext-ext-argparse

Thoughts?

(Obviously a good workaround is to create a default command and print the help text.)

**Comment by derks** [comment]
This is an odd situation yeah... I had to look at the source to remember, but there is `ArgparseController.Meta.default_func` which is defined as `default` by... well, default.

 * http://builtoncement.com/2.10/api/ext/ext_argparse.html#cement.ext.ext_argparse.ArgparseController.Meta.default_func

> Function to call if no sub-command is passed. Note that this can not start with an _ due to backward compatibility restraints in how Cement discovers and maps commands.
> 
> Note: Currently, default function/sub-command only functions on Python > 3.4. Previous versions of Python/Argparse will throw the exception error: too few arguments.

And wehre you're seeing the error:

 * https://github.com/datafolklabs/cement/blob/master/cement/ext/ext_argparse.py#L919


So, yes... agreed the docs can be improved... but effectively, you are getting a FrameworkError because you are (by default) trying to use a function that doesn't exist  as per `ArgparseController.Meta.default_func` (because no command/sub-command was passed... so something has to happen, somewhere.

So, if you were on Python < 3.4 you would never get that FrameworkError because Argparse would have already thrown the `too few arguments` error... but since you're using Python >= 3.4 you are because you didn't pass anything and you haven't defined a default function to handle the situation.

Does that make sense?  Any suggestion on how to improve that... please help! ;)

**Comment by jtpereyda** [comment]
A few possibilities I can think of:

1. Refactor to present that same too few arguments error as in Python < 3.4. This might involve a lot of changes. It may not make a lot of sense if `argparse` in Python >= 3.4 doesn't support raising an error in this condition.
2. Implement default function to print help by default unless overridden by an implementation. This is in line with common behavior, e.g. running `git` with no arguments.
3. Use `abc` to make an abstract function named `default` that must be overridden. This adds complexity, but at least the interface makes the requirement explicit (if not obvious).

I like 2 for being easy to implement, user-friendly, and a relatively safe default. I'm not sure if all developers would want this, but it is better than raising an exception, I think. The docs could be updated to note that there is now a default default.

**Comment by derks** [comment]
@jtpereyda I've been thinking about this a bit more trying to remember why a `default` function wasn't implemented as part of `ArgparseController` before.  If I recall correctly, this was a design decision based on the idea that we don't want the framework imposing too much on the developer, such as forcing a `default` function (named default, etc).  Implementing a default function would mean `expose()`ing it .. which isn't ideal, especially if the developer chooses a different default func.

I think the proper change here is raising a more appropriate exception such as `FrameworkError("No sub-command given, and no `default` function defined. See this-part-of-the-documation")` or something like that.

Regardless, improving the documentation will make it clear what is required of the developer.  I can't really think of a situation where a developer wouldn't want a default function... whether that is showing help, or performing some default action.  Therefore it is up to the developer to define what that default action is... the framework shouldn't enforce it by explicitly defining anything.  Right now an exception is raised as a result of nothing being defined which I think is appropriate, just not as clear as it needs to be as to why that exception is happening.

**Comment by jtpereyda** [comment]
@derks Thanks for implementing and maintain `cement`, and for checking out my issue/PR. This is a killer framework and I'm glad its' around to use. :)

That makes sense on imposing less behavior. For my purposes, I'd want the framework to do something (anything), but not raise an exception. Maybe not everyone feels that way.

The nice thing about some kind of default is that you can declare an empty `ArgParseController` that is functionally valid.

```python
class TrivialAppController(ArgParseController):
    pass
```

Which is slick IMO.

Would delivering a usage error would make sense as a default action that doesn't impose too much? If the developer specified no default function, they probably just didn't want the app to have a default function. I would have done this in the PR but couldn't figure it out in time.

**Comment by jtpereyda** [comment]
> Implementing a default function would mean expose()ing it .. which isn't ideal, especially if the developer chooses a different default func.

Oh, must functions be `expose()`d? This is what I did at first, but `expose()` makes it show up as a command named "default". After I took off the `expose()` I thought it looked better, since the user doesn't see {default} on the help text.

```
C:\Users\joshpere\code\practice>python3 c.py -h
usage: myapp [-h] [--debug] [--quiet] {} ...

optional arguments:
  -h, --help  show this help message and exit
  --debug     toggle debug output
  --quiet     suppress all output

sub-commands:
  {}
```

**Comment by derks** [comment]
Now that you say that, I think in this case ... in the way the fall-back `default` is called... I guess it doesn't need to be exposed.

I'll think about this further... still not sure I want to impose the default function as it implies what the default should do.  Raising an exception says, "Hey developer...  something is missing that you are required to add here".  You know?

**Comment by jtpereyda** [comment]
> Raising an exception says, "Hey developer... something is missing that you are required to add here". You know?

Fair enough

**Comment by derks** [comment]
@jtpereyda as an aside, you can use `@expose(hide=True)` so that the default (or other functions) don't show in `--help`.

**Comment by LeeFowlerCU** [comment]
@derks `@expose(hide=True)` does not appear to be working with controllers subclassing from `ArgparseController`. Using the default `boss` template generates a base controller subclassing from `ArgparseController` with a default command that is supposed to be hidden from `--help` but is not.

**Comment by derks** [comment]
The `default` is a special case ... due to limitations in Argparse, it's not possible to completely hide it.  I believe what you'r seeing is that it is included in the short list... i.e. `{default,other-command,etc}`... but it still should be hidden from the long form of commands (meaning, it's not listed with the other commands with their description).  Correct?

Can you confirm that all other commands do hide, it's just the default that doesn't?

**Comment by LeeFowlerCU** [comment]
I can confirm that `@expose(hide=True)` does hide the commands from the `sub-commands:` list but still shows them both on the usage line:

`usage: conduit [-h] [--debug] [--quiet] {default,test-command} ...`

and on the sub-commands shortlist:

```
sub-commands:
  {default,test-command}
```

I'd argue that for every other command other than `default` this is probably the intended behavior. But, since the `default` command is enforced by the framework, the `default` command showing those places is confusing clutter. Users will almost always invoke a command via `<command>` as opposed to `<command> default`. 

Having it show in those lists is both confusing from a user-perspective and aesthetically displeasing from a developer perspective.

**Comment by derks** [comment]
@LeeFowlerCU I agree with your sentiments about the default command showing in `--help`, but as mentioned that is an issue upstream in Python that I can't work around.  To that point however, it would be nice of the framework to allow you to not have a `default` function at all so that you can choose to work around it if you want to.

Regarding the command usage... as far as I know, there is not a case where you **have** to include `default` in the command.  `app -options command -options` should work the same as `app -options command default -options` ... IIRC but I could be wrong.

**Comment by derks** [comment]
@LeeFowlerCU I just discovered a happy workaround that doesn't even require framework changes.  If you set `YourController.Meta.default_func = '_default'` and add a `_default()` method...  you get the best of both where the `_default` doesn't show in help output, but it is called if no subcommands were passed (so you can handle it however you want).  Which make this change in Cement 3, but due to backward compat can't make that the default in Cement 2.

**Comment by derks** [comment]
This was finalized in portland (now Cement 3.0) a while ago.. the `_default` approach is now the builtin default, and solves this issue.
