### ISSUE TITLE
Inappropriate ioctl for device

### ISSUE THREAD

**Issue by kjenney** [datafolklabs/cement#488]
I'm getting an error when attempting to run Cement within a Docker container. It looks like this was supposed to have been addressed in https://github.com/datafolklabs/cement/issues/401 but I'm still getting the old error.

**System Information**

- Cement Version: 2.10.2
- Python Version: 2.7
- Operating System and Version: Debian Jessie

**Steps to Reproduce (Bugs Only)**

- Step 1: Install cement via pip
- Step 2: Run script: python deployit.py

**Example**

```python
###!/usr/bin/env python

# Script to provision infrastructure to a datacenter with Terraform and deploy applications using Ansible

import sys
from cement.core.foundation import CementApp
from cement.core import hook
from cement.utils.misc import init_defaults

#print 'Number of arguments:', len(sys.argv), 'arguments.'
#print 'Argument List:', str(sys.argv)

from cement.core.foundation import CementApp
from cement.core import hook
from cement.utils.misc import init_defaults

# define our default configuration options
defaults = init_defaults('deployit')
defaults['deployit']['debug'] = False
defaults['deployit']['some_param'] = 'some value'

# define any hook functions here
def my_cleanup_hook(app):
    pass

# define the application class
class Deployit(CementApp):
    class Meta:
        label = 'deployit'
        config_defaults = defaults
        extensions = ['daemon', 'memcached', 'json', 'yaml']
        hooks = [
            ('pre_close', my_cleanup_hook),
        ]

with Deployit() as app:
    # add arguments to the parser
    app.args.add_argument('-f', '--foo', action='store', metavar='STR',
                          help='the notorious foo option')

    # log stuff
    app.log.debug("About to Deploy It!")

    # run the application
    app.run()

    # continue with additional application logic
    if app.pargs.foo:
        app.log.info("Received option: foo => %s" % app.pargs.foo)
```
Error:

```
$ docker run --rm deployit
Traceback (most recent call last):
  File "deployit.py", line 36, in <module>
    with Deployit() as app:
  File "/usr/local/lib/python2.7/site-packages/cement/core/foundation.py", line 1494, in __enter__
    self.setup()
  File "/usr/local/lib/python2.7/site-packages/cement/core/foundation.py", line 860, in setup
    for res in self.hook.run('post_setup', self):
  File "/usr/local/lib/python2.7/site-packages/cement/core/hook.py", line 150, in run
    res = hook[2](*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/cement/ext/ext_daemon.py", line 377, in extend_app
    user = pwd.getpwnam(os.getlogin())
OSError: [Errno 25] Inappropriate ioctl for device
```

**Comment by derks** [comment]
This is fixed in `master`, however there has not been a new release for Cement 2.10.x since then, so it is not deployed to PyPi currently. I've been spending all of my time working on Cement 3.

If this is a critical fix, I can shift gears to work on getting Cement 2.10.4 out the door... however, a couple questions:

- Would it be suitable to just apply a patch as part of your Dockerfile build?  The changes are minimal:  https://github.com/datafolklabs/cement/commit/496f020fe850ac5fb23c6811e5f52310ba6b2a17
- Would it be suitable to use git master (Cement 2.10.x)?  Not ideal, but might be OK based on your use case / risk profile
- If you're running in Docker, do you still need the daemon extension? Generally in Docker you are running in the foreground and not daemonizing... (though I know there are other features of the daemon extension that you might want/need still).

**Comment by kevdowney** [comment]
+1 on a fixed release for this.

**Comment by derks** [comment]
Thank you all for the feedback.  I have pushed out Cement 2.10.4 with the fixes for above.
