### ISSUE TITLE
Is this project still maintained ?

### ISSUE THREAD

**Issue by botzill** [datafolklabs/cement#577]
Hi.

I find this project really cool but seems not so much activity lately, I want to ask if you still work on it and what is the status in general?

Thx1

**Comment by derks** [comment]
@botzill hello, yes this project is active and I use it daily for many projects. That said, I tend to work in sprints for features and major releases.  A lot of time went into releasing and redocumenting Cement 3.0 and there have not been any major bugs or issues so I have not sprinted on that since release.

I do see that I've missed some Git issues come through and do admit that I've not been keeping up with it well.  Worse case is, if you submit an issue and don't hear anything just keep pinging me @derks until I do. It's usually just that it slips through email and I don't see it.

**Comment by botzill** [comment]
Hi @derks!

Thx for update. The reason I asked about it is because this is a too cool proj to be left alone. 

OK, then I will use it as well in my project  and keep an eye on it.

Thx.

**Comment by GabrielC101** [comment]
I'm so happy this is being maintained. Your work is very appreciated!
