### ISSUE TITLE
Project still active and reliable?

### ISSUE THREAD

**Issue by TomFreudenberg** [datafolklabs/cement#600]
Hi,

we are new on this project and had made our way through the tutorial. Still impressed by the framework but wondering why so less activity on issues and documentation. The docs at https://docs.builtoncement.com/getting-started/beginner-tutorial are outdated for 3 years by now.

In case that we want to start a bigger project I would be happy if someone may guide me if it is fine to start with cement?

Thanks for work and feedback
Tom

**Comment by derks** [comment]
@TomFreudenberg thank you for the interest, and for the question. Has it been 3 years... wow.  I assure you Cement is stable and maintained... without any plans of abandoning it in the near or far future.  Documentation hasn't changed in a while, but there has been activity, and the last release on PyPi (3.0.4) was May 2019. As a solo maintainer it has unfortunately not been under active development since the last major release due.... but I myself continue to use it as the foundation for everything command-line/daemon/etc that I do.   

I spent a lot of time refactoring and re-documenting the Cement 3 release, which was not a huge change from Cement 2. I removed the bad, and perfected the good (my opinion obviously)... and further expanded on framework extensions. Often times, if there is a question/request for something Cement doesn't do out of the box, it is very easy/straightforward to create an extension for it or subclass and expand on an existing extension. There have not been any major bugs or blockers since the Cement 3 release.

I also found out recently that a lot (not all) of my Github notifications were going to spam and I missed the most recent lot of issues on this project. That is now resolved and there should not be as much delay in response as there has been. 

All that said, I greatly appreciate this feedback and hate the idea that the project is at times perceived to be dead.  I will take that as a sign that I need to get back to regular sprints... even if they are small maintenance releases.  Please open issues for bugs/features/questions for any and everything.

**Comment by TomFreudenberg** [comment]
Hi @derks 

Great to get your warm and open response. I know the situation being a solo person maintainer - its not easy all the time :-)

So we will continue using your excellent cement 3 CLI framework.

Thanks for your effort and spending this as an open source project.

Tom
