### ISSUE TITLE
Move cement.cli baked in dependencies to cement[cli] virtual package

### ISSUE THREAD

**Issue by derks** [datafolklabs/cement#679]
Currently cement includes a number of dependent libraries in `cement.cli.contrib`, rather than depending on them externally. This was due to the design requirement that Cement core library does not have any external dependencies.  With virtual packages, these can now be removed and we can include the deps for the CLI tools via `cement[cli]`. 

I think we can still include `cement` cli tool, but catch import errors and suggest installing `cement[cli]` to use the cli.

**Comment by derks** [comment]
@sigma67 appreciate your work here.  I'm curious what your opinion is on backward compatibility? The `cement` cli tool is primarily focussed on development, however anyone pulling in `pip install cement` and expecting the cli to be there will break (thinking CI/CD pipelines, etc).

Cement is pretty strict about no breaking changes in minor x.y.Z point release... but brancing to a new x.Y.z release incurs overhead so I'd be in favor of pushing this forward as it is less likely to affect anything in production.

Anyone else's opinions welcome.

**Comment by sigma67** [comment]
Thanks, we aren't using the CLI so no problem for us. 

Alternative option, one could add the dependencies to default dependencies for now, although that would also be a "breaking" change because there previously were no dependencies (albeit not a big deal). Then add a deprecation notice that the CLI dependencies will be moved to the cli group, in case this has not been communicated.

I think going straight for the optional group would be the better option and shouldn't be a problem - users can just pin the older version if they don't want the extra.

**Comment by sigma67** [comment]
@derks how would you like to proceed here?

**Comment by derks** [comment]
@sigma67 I am sprinting this week and was planning to figure it out. I'm inclined to push forward on moving deps to cement[cli] and give notice prior to release that some automation could "break". The breaking change does not affect the core library, or apps built on cement... and therefore does not go against philosophy of "no breaking changes in minor releases". 

I will hopefully close this out this week.

**Comment by sigma67** [comment]
Great, thanks for the update

**Comment by derks** [comment]
@sigma67 this is resolved in `main` and will be included in 3.0.12.
